version: '3'

services:
  caldera:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: "UTC"
        WIN_BUILD: "true"
    image: caldera:latest
    ports:
      - "8888:8888"
      - "8443:8443"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8853:8853"
      - "8022:8022"
      - "2222:2222"
    volumes:
      - ./:/usr/src/app
    command: --log DEBUG
    networks:
      - caldera-network
    container_name: caldera

  agent-1:
    build:
      context: ./ubuntu-agent
      dockerfile: Dockerfile
    container_name: agent-1
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - caldera-network

  agent-2:
    build:
      context: ./ubuntu-agent
      dockerfile: Dockerfile
    container_name: agent-2
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - caldera-network

  discover-1:
    build:
      context: ./ubuntu-agent
      dockerfile: Dockerfile
    container_name: discover-1
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - caldera-network

networks:
  caldera-network:
    driver: bridge
